### ISSUE TITLE
Assignment Progress

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-200-fall-2023/cache-conundrum-assignment#1]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## Timing

- [ ] hello_cache&#x2F;main.c implements gettimeofday to record code start and end time
- [ ] hello_cache&#x2F;main.c implements net_time calcuation
- [ ] space_is_the_place&#x2F;main.c implements gettimeofday to record code start and end time
- [ ] space_is_the_place&#x2F;main.c implements net_time to calculate runtime of code sections
- [ ] space_is_the_place&#x2F;main.c uses the sum_array_nocache function to run uncached operations
- [ ] matrix_mania&#x2F;main.c implements gettimeofday to record code start and end time of each section of interest
- [ ] matrix_mania&#x2F;main.c implements net_time to calculate runtime of code sections
- [ ] bad_blink&#x2F;main.c implements net_time to calculate runtime of code section

## TODO

- [ ] hello_cache&#x2F;main.c contains no TODOs
- [ ] space_is_the_place&#x2F;main.c contains no TODOs
- [ ] matrix_mania&#x2F;main.c contains no TODOs

## Cache rates

- [ ] hello_cache&#x2F;main.c implements cache hit count calculation
- [ ] hello_cache&#x2F;main.c implements cache miss count calculation
- [ ] hello_cache&#x2F;main.c implements cache hit rate calculation
- [ ] hello_cache&#x2F;main.c implements cache miss rate calculation
- [ ] space_is_the_place&#x2F;main.c implements cache hit count calculation
- [ ] space_is_the_place&#x2F;main.c implements cache miss count calculation
- [ ] space_is_the_place&#x2F;main.c implements cache hit rate calculation
- [ ] space_is_the_place&#x2F;main.c implements cache miss rate calculation
- [ ] matrix_mania&#x2F;main.c implements cache hit count calculation for both functions
- [ ] matrix_mania&#x2F;main.c implements cache miss count calculation for both functions
- [ ] matrix_mania&#x2F;main.c implements cache hit rate calculation for both functions
- [ ] matrix_mania&#x2F;main.c implements cache miss rate calculation for both functions
- [ ] bad_blink&#x2F;main.c implements cache hit count calculation
- [ ] bad_blink&#x2F;main.c implements cache miss count calculation
- [ ] bad_blink&#x2F;main.c implements cache hit rate calculation
- [ ] bad_blink&#x2F;main.c implements cache miss rate calculation

## TODOs

- [ ] docs&#x2F;report.md responds to all questions

## Percent complete

Based on the checks achieved, this assignment is `0%` complete.
